### ISSUE TITLE
Port Issue perhaps?  "You have not filled out your merchant profile"

### ISSUE THREAD

**Issue by jasonyohon** [coinbase/coinbase-magento#20]
I am suddenly I am getting an error with Coinbase orders. Before the sudden error I was using Coinbase extension successfully for months.

In the frontend I get "There was an error processing your order. Please contact us or try again later."

Backend log says "Double check your API Key and Secret. You have not filled out your merchant profile. Please enter your information in the Profile section."  (complete trace below)

The API Key and Secret are definitely correct. I have checked and rechecked it. But this issue started out of the blue without me changing either. No new extensions or code changes to the site that I can think of.  

What port does Coinbase use? I wonder if my firewall closed a port that Coinbase needs to use?  

Logged Error:
'Exception' with message 'Could not generate checkout page. Double check your API Key and Secret. You have not filled out your merchant profile. Please enter your information in the Profile section.' in /app/code/community/Coinbase/Coinbase/Model/PaymentMethod.php:108
Stack trace:
0. /app/code/core/Mage/Sales/Model/Order/Payment.php(1026): Coinbase_Coinbase_Model_PaymentMethod->authorize(Object(Mage_Sales_Model_Order_Payment), 28.17)
1. /app/code/core/Mage/Sales/Model/Order/Payment.php(311): Mage_Sales_Model_Order_Payment->_authorize(true, 28.17)
2. /app/code/core/Mage/Sales/Model/Order.php(877): Mage_Sales_Model_Order_Payment->place()
3. /app/code/core/Mage/Sales/Model/Order.php(1095): Mage_Sales_Model_Order->_placePayment()
4. [internal function]: Mage_Sales_Model_Order->place()
5. /app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
6. /app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
7. /app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
8. /app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
9. /app/code/local/TM/FireCheckout/Model/Type/Standard.php(1125): Mage_Sales_Model_Service_Quote->submitAll()
10. /app/code/local/TM/FireCheckout/controllers/IndexController.php(1387): TM_FireCheckout_Model_Type_Standard->saveOrder()
11. /app/code/core/Mage/Core/Controller/Varien/Action.php(419): TM_FireCheckout_IndexController->saveOrderAction()
12. /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
13. /app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
14. /app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
15. /app/Mage.php(683): Mage_Core_Model_App->run(Array)
16. /index.php(87): Mage::run('', 'store')

**Comment by aianus** [comment]
What about this part of the error?

`You have not filled out your merchant profile. Please enter your information in the Profile section.`

Have you filled out your merchant profile information?

**Comment by jasonyohon** [comment]
OK, I'm a dummy. Just found a warning from Coinbase about completing the Merchant Profile in my spam folder. Based on the warning in the stack trace I thought "Merchant Profile" was the API info section in the Magento extension. Updated profile, now fixed. Thanks.

**Comment by aianus** [comment]
No problem, glad to hear it's working now :)
