### ISSUE TITLE
Can't natively edit or cancel orders if paid by Bitocin

### ISSUE THREAD

**Issue by 88kbbq** [coinbase/coinbase-magento#22]
The content header form buttons are all missing in orders placed with Bitcoin. I understand that if a Bitcoin payment went through for an order, there is no way to refund from within Magento, but at least add the ability to cancel orders for manual refund. We have customers who "accidentally" used Bitcoin to put through orders. The order goes through to Magento but then they cancel out of Coinbase and just call me to edit the order. My hands are tied! I have to ask them to redo the order. Luckily they did, but I can imagine somebody on the fence about a purchase would just say forget it and cancel the entire order.

**Comment by aianus** [comment]
As far as I can tell, this is a limitation in Magento itself, not in the Coinbase plugin.

As a workaround it does seem to be possible to set up your own cron job to periodically remove orders stuck in payment_pending: http://inchoo.net/magento/cancel-pending-orders/
