### ISSUE TITLE
Coinbase and Magento

### ISSUE THREAD

**Issue by bkbeltgal** [coinbase/coinbase-magento#23]
I got the ability for customers to pay with bitcoin working using this extension.  :-)

The two behaviors I don't like and that I would want to solve:

1) A Customer's order can show in Magento admin even though the bitcoin payment wasn't completed. 

2) If the payment is not completed all the way the ... the customer's Shopping cart clears... so
if a customer changes their mind and wants to pay another way... they have to add their items to their shopping cart again.

Anybody have any good solutions?

Thanks,
Emily

**Comment by aianus** [comment]
I don't think there's any way around these issues. Once redirected to Coinbase, there is no guarantee the user will ever return so before that point we have to clear the cart and create a new order pending payment.
