### ISSUE TITLE
There was an error processing your order. Please contact us or try again later."

### ISSUE THREAD

**Issue by gingabox** [coinbase/coinbase-magento#26]
Hello we are experiencing a problem with the extension.  It installs fine, but when we try to process an order, it gives us an error which says "There was an error processing your order. Please contact us or try again later."

I've enabled logging and am getting the exception below.  

I did set up API with secret key and have permissions set to all.  I have entered them correctly, so not sure what the issue is.

Thank you in advance for your help!

Here is the exception log entry:

2016-02-09T12:47:48+00:00 ERR (3): 
exception 'Exception' with message 'Could not generate checkout page. Double check your API Key and Secret. Status code 401' in /chroot/home/root/domain/html/app/code/community/Coinbase/Coinbase/Model/PaymentMethod.php:107
Stack trace:
#0 /chroot/home/root/domain/html/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): Coinbase_Coinbase_Model_PaymentMethod->authorize(Object(Mage_Sales_Model_Order_Payment), 9.71)
#1 /chroot/home/root/domain/html/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 9.71)
#2 /chroot/home/root/domain/html/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#3 /chroot/home/root/domain/html/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#4 [internal function]: Mage_Sales_Model_Order->place()
#5 /chroot/home/root/domain/html/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#6 /chroot/home/root/domain/html/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#7 /chroot/home/root/domain/html/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#8 /chroot/home/root/domain/html/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#9 /chroot/home/root/domain/html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(784): Mage_Sales_Model_Service_Quote->submitAll()
#10 [internal function]: Mage_Checkout_Model_Type_Onepage->saveOrder()
#11 /chroot/home/root/domain/html/app/code/community/EcomDev/CheckItOut/Model/Type/Onepage.php(446): call_user_func_array(Array, Array)
#12 /chroot/home/root/domain/html/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): EcomDev_CheckItOut_Model_Type_Onepage->__call('saveOrder', Array)
#13 /chroot/home/root/domain/html/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): EcomDev_CheckItOut_Model_Type_Onepage->saveOrder()
#14 /chroot/home/root/domain/html/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#15 /chroot/home/root/domain/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#16 /chroot/home/root/domain/html/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /chroot/home/root/domain/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#18 /chroot/home/root/domain/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 /chroot/home/root/domain/html/index.php(87): Mage::run('', 'store')
#20 {main}

**Comment by aianus** [comment]
The current version of the Magento plugin is using Coinbase API v1 (v2 is coming soon).

Please make sure your API key has the 'merchant' permission checked under 'API v1 permissions (legacy)'.

<img width="544" alt="screen shot 2016-02-09 at 10 52 17 am" src="https://cloud.githubusercontent.com/assets/1322087/12921463/6d42bf28-cf1b-11e5-8840-14a90a12353d.png">

No other permissions are necessary and none should be checked (otherwise, if the key gets compromised, an attacker will be able to drain your Coinbase account of money).

**Comment by gingabox** [comment]
Hello Alex,
I am curious if you might be available to work customization for the
Coinbase for Magento extension.  We are trying to create some way to allow
our customers to complete the payment process without leaving our site,
something similar to how bitmaintech.com does their bitcoin checkout.
Would this be something you have time to work on?   If so, please let me
know what you would charge for this.

Thank you very much
Ryan

**Comment by aianus** [comment]
Hi Ryan,

Let me get back to you later this week after I upgrade the magento plugin
to use v2 of our API. I haven't looked at this in a while so I'm not sure
if what you're asking for is possible or what it would entail.

Cheers,
Alex

**Comment by gingabox** [comment]
Fantastic, thank you Alex, very much appreciated.  

Thanks
Ryan

**Comment by coreywiley** [comment]
I'm getting this error as well with the exception:
`Could not generate checkout page. Double check your API Key and Secret Status. code 401' in /var/www/includes/src/Coinbase_Coinbase_Model_PaymentMethod.php:107`.

I'm running Magento Community 1.9.3.7 & just used the master version download link on the readme.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
