### ISSUE TITLE
Add BTC as a store currency option

### ISSUE THREAD

**Issue by forcoinsllc** [coinbase/coinbase-magento#4]
Module installs fine on ver. 1.7.0.2. Was very easy and everything just worked.... at first.

I made a test order from the customer's view. It went through fine (though there was some changes I would prefer to have made, but that's a different story)

Customer was given invoice, I paid, everything went fine, it even went on to show the order number in the browser and say that your order has been completed thankyou... yada yada yada.

Now, from the admin side, I did not get a sales email, which was odd, so I signed in and clicked on the transaction and it says the following 2 entries:
Dec 22, 2013 8:20:10 PM|Payment Review
Customer Notification Not Applicable
Authorizing amount of ฿0.03250 is pending approval on gateway. 

THEN 

Dec 22, 2013 8:21:04 PM|Suspected Fraud
Customer Notification Not Applicable
Paid with Coinbase order 2JH8NGYC. Order is suspended as its capture amount ฿32,500.00000 is suspected to be fraudulent. Transaction ID: "2JH8NGYC". 

Somehow a decimal place is getting thrown around incorrectly. Payment came to my coinbase account correctly. (so fund transfer was fine) but the call back from coinbase with transaction order number seems to be way incorrect (thought I would not have minded a 32,500 bitcoin order. haha. 

Please help! Thanks!

Extra Info:
I have 4 decimal places of precision on magento. I have all items priced in BTC on the site, there is no usd pricing.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
